In [34]:
import numpy as np

In [35]:
new_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
np.reshape(new_array,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
new_array.reshape((2,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [38]:
#Can we Reshape to any shape?
      # ==> Yes, as long as element required for reshaping are equal in both shapes.



In [39]:
array_1D = np.array([1,2,3,4,5,6,7,8])
array_1D

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
np.reshape(array_1D,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
array_1D.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
array_1D.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [43]:
# Create a array of 8 elements and try to reshape using (3,3)\
array_a = ([1,2,3,4,5,6,7,8])
array_a
 

[1, 2, 3, 4, 5, 6, 7, 8]

In [44]:
np.reshape(array_a,(3,3))

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
'''This process raise an exception , since there are 8 elements and (3,3) need 9 elements so raise an exception'''

In [ ]:
#Joining Array
#Concatenation
    #We Pass sequence of array that we want to the concatenate() function.
    #After Concatenating dimension of resulting array will be same as that of individual array.
    #Order of concatination will be based on the order in which array are passed to the concatenate()function.

In [ ]:
arr1 = np.array([1,1,1,1])
arr2 = np.array([2,2,2,2])

concat_arr = np.concatenate((arr1, arr2))
concat_arr

array([1, 1, 1, 1, 2, 2, 2, 2])

In [ ]:
#Concat 2D array
array_one_2D = np.array([[1,2,3,4],[5,6,7,8,]])
array_two_2D = np.array([[4,5,6,3],[1,2,3,4]])
concat_arr = np.concatenate((array_one_2D,array_two_2D))
concat_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 3],
       [1, 2, 3, 4]])

In [ ]:
np.concatenate ((array_one_2D,array_two_2D), axis=1)

array([[1, 2, 3, 4, 4, 5, 6, 3],
       [5, 6, 7, 8, 1, 2, 3, 4]])

In [ ]:
'''#Splitting Array
- Splitting is a reverse operations of joining
- Joining merges multiple array into one.
- Splitting breaks one array into multiple one.
- can be implemented using numpy function
    -numpy.split()
    -numpy.array_split()
- We pass array we want to split and the number of split.
- Sub-arrays obtained after splitting is only view of the original arrays.
     - Change made to the sub-array also reflect changes in the original array.'''

In [ ]:
#Splitting 1D array i.e [1,2,3,4,5,6]into 4 parts

array_ = np.array([1,2,3,4,5,6])
np.split(array_ ,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
np.array_split(array_ ,5)


[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

In [ ]:
split_array = np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9],
                        [10,11,12],
                        [13,14,15],
                        [16,17,18]]) 
np.split(split_array,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [ ]:
np.array_split(split_array,4)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [ ]:
np.array_split(split_array,4,axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([], shape=(6, 0), dtype=int32)]

In [ ]:
'''Numpy as a Universal Function 
---- Looping over the array to perform repeated task like addition,subtraction,etc on each array element are common.
---- Computation time to perform such repeated task increase with relatively larger data.
---- Numpy makes this faster by using vectorized operations, implemented through unfuncs
---Types:
   Unary Ufuncs
   Binary Ufuncs

Operations:
np.add() => Element wise addition
np.subtract() => Ekement Subtraction'''

In [45]:
#Numpy Universal Function
import time
x1 = np.arange(1 ,1000)
x2 = np.arange(1,1000)

mul = np.zeros(x1.shape)

start_time = time.process_time()

for i in range(len(x1)):
    mul[i] = x1[i] * x2[2]

end_time = time.process_time()

print(end_time - start_time)

0.0


In [ ]:
# Vectorization

In [46]:
a = np.array ([1,2,3,4])
b = 2
print(a+b)

[3 4 5 6]


In [47]:
a = np.array ([1,2,3])
b = np.array([[10],[20],[30]])

In [48]:
a.shape

(3,)

In [49]:
b.shape

(3, 1)

In [50]:
print(a+b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [51]:
a = np.array ([1,3])
b = np.array ([1,2,3])
print(a+b)





ValueError: operands could not be broadcast together with shapes (2,) (3,) 